### ISSUE TITLE
AccessViolation

### ISSUE THREAD

**Issue by ameisen** [ameisen/SV-SpriteMaster#25]
Log Attached.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SpriteMaster.GL.Texture2DExt+<>c__DisplayClass30_0`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<SetDataInternal>b__4()
   at SpriteMaster.GL.Texture2DExt+<>c__DisplayClass30_0`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<SetDataInternal>b__0()
   at SpriteMaster.GL.Texture2DExt.SetDataInternal[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.Xna.Framework.Graphics.Texture2D, Int32, System.Nullable`1<SpriteMaster.Types.Bounds>, SpriteMaster.Types.PointerSpan`1<Byte>, Boolean, Boolean)
   at SpriteMaster.Harmonize.Patches.PTexture2D.OnPlatformSetDataPre[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.Xna.Framework.Graphics.Texture2D, Int32, Int32, Microsoft.Xna.Framework.Rectangle, Byte[], Int32, Int32)
   at DynamicClass.Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData_PatchedBy<DigitalCarbide.SpriteMaster>(Microsoft.Xna.Framework.Graphics.Texture2D, Int32, Byte[], Int32, Int32)
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Byte[])
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformFromStream(Microsoft.Xna.Framework.Graphics.GraphicsDevice, System.IO.Stream)
   at DynamicClass.Microsoft.Xna.Framework.Graphics.Texture2D.FromStream_PatchedBy<Platonymous.PyTK>(Microsoft.Xna.Framework.Graphics.GraphicsDevice, System.IO.Stream)
   at StardewModdingAPI.Framework.ContentManagers.ModContentManager.LoadImageFile[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](StardewModdingAPI.IAssetName, System.IO.FileInfo)
   at StardewModdingAPI.Framework.ContentManagers.ModContentManager.LoadExact[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](StardewModdingAPI.IAssetName, Boolean)
   at StardewModdingAPI.Framework.ModHelpers.ModContentHelper.Load[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String)
   at DynamicGameAssets.PackData.ContentPack.GetTexture(System.String, Int32, Int32)
   at DynamicGameAssets.Game.CustomBasicFurniture.DoInit(DynamicGameAssets.PackData.FurniturePackData)
   at DynamicGameAssets.PackData.FurniturePackData.ToItem()
   at DynamicGameAssets.ItemAbstraction.Create()
   at DynamicGameAssets.Mod.RefreshShopEntries()
   at DynamicGameAssets.Mod.OnDayStarted(System.Object, StardewModdingAPI.Events.DayStartedEventArgs)
   at StardewModdingAPI.Framework.Events.ManagedEvent`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Raise(System.__Canon)
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(StardewModdingAPI.Framework.SGame, Microsoft.Xna.Framework.GameTime, System.Action)
   at StardewModdingAPI.Framework.SGame.Update(Microsoft.Xna.Framework.GameTime)
   at StardewValley.GameRunner.Update(Microsoft.Xna.Framework.GameTime)
   at StardewModdingAPI.Framework.SCore.OnGameUpdating(Microsoft.Xna.Framework.GameTime, System.Action)
   at Microsoft.Xna.Framework.Game.DoUpdate(Microsoft.Xna.Framework.GameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(Microsoft.Xna.Framework.GameRunBehavior)
   at StardewModdingAPI.Framework.SCore.RunInteractively()
   at StardewModdingAPI.Program.Start(System.String[])
   at StardewModdingAPI.Program.Main(System.String[])
```

```
[SpriteMaster] [Dump] System Information:
        Architecture: x64
        Number of Cores: 12
        OS Version: Microsoft Windows NT 10.0.22621.0
        CPU Information
                Brand             : AMD
                Microarchitecture : Zen 2 'Lucienne'
                Family            : 143
                Model             : 104
                Stepping          : 1
                Type              : OriginalOem
                Instruction Sets:
                        SSSE3  : true (enabled)
                        SSE4.1 : true (enabled)
                        BMI2   : true (enabled)
                        AVX2   : true (enabled)
        Total Committed Memory: 596.56 MiB
        Total Available Memory: 15.33 GiB
        Graphics Adapter
                Description    : AMD Radeon(TM) Graphics
                Vendor         : AMD
                Dedicated      : True

[SpriteMaster] [Dump] GLExt Dump:
  Context Version: 4.6
  CreateTextures              : True
  TexStorage2D                : True
  TextureStorage2D            : True
  TextureStorage2DExt         : True
  CopyImageSubData            : True
  GetInteger64v               : False
  GetTexImage                 : True
  GetTextureSubImage          : True
  GetCompressedTexImage       : True
  GetCompressedTextureSubImage: True
  DrawElements                : True
  DrawRangeElements           : True
  VertexAttribPointer         : True
  BindBuffer                  : True
  BufferData                  : True
  VertexAttribDivisor         : True
  GetTexParameteriv           : True
  _bindTexture                : True
  _pixelStorei                : True
```

[access_violation_log.txt](https://github.com/ameisen/SV-SpriteMaster/files/11473433/access_violation_log.txt)

**Comment by ameisen** [comment]
Re: Discord `Sveta#8048`
