### ISSUE TITLE
Smapi update

### ISSUE THREAD

**Issue by geenaxion** [ameisen/SV-SpriteMaster#28]
On Steam Deck/Linux, Spritemaster not working with the latest Smapi 3.18.5 version

**Comment by geenaxion** [comment]
[Save] Exception: ArgumentNullException : Value cannot be null. (Parameter 'path')at System.IO.File.CreateText(String path)
at SpriteMaster.Configuration.Serialize.Save(String configPath) in D:\SpriteMaster\SpriteMaster\Configuration\Serialize.cs:line 695

this is the 1st time it showed up when i updated

**Comment by geenaxion** [comment]
https://smapi.io/log/f79db2ec227c4b50adb9957f596ee533
